# supabase/config.toml

# The project_id you already had
project_id = "bsrarbbjzftgtkiegqbh"

# This defines settings specifically for the 'process-online-payment' function
[functions.process-online-payment]

  # This allows the function to access specific environment variables
  #allow_env = ["RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET"]

  # This allows the function to make network requests to a specific domain.
  # For security, it's best to specify only the domain you need.
  #allow_net = ["api.razorpay.com"]
[functions.create-razorpay-order]
enabled = true
verify_jwt = true
import_map = "./functions/create-razorpay-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-razorpay-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-razorpay-order/*.html" ]

[functions.verify-and-process-payment]
enabled = true
verify_jwt = true
import_map = "./functions/verify-and-process-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-and-process-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-and-process-payment/*.html" ]
