// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsrarbbjzftgtkiegqbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcmFyYmJqemZ0Z3RraWVncWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjkzNTYsImV4cCI6MjA2Mzc0NTM1Nn0.9hnhhAsIrQ0jdwxZN4PTBi_jjSsvQN0Hg0GAppKJy1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);